name: VotePlus
main: fap.voteplus.VotePlusMain
version: "1.0.0"
author: FAP Network
api: ["1.0.0"]
commands:
  vote:
    description: 投票功能
  ban:
    description: VotePlus Ban
  addmoney:
    description: VotePlus MoneyAPI
  reducemoney:
    description: VotePlus MoneyAPI
  getmoney:
    description: VotePlus MoneyAPI